modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/ThreeTAG/PantheonSent/issues"

[[mods]]
modId = "pantheonsent"
version = "${version}"
displayName = "PantheonSent"
authors = "Lucraft"
description = '''
Channel the power of the gods and serve their will!
'''
logoFile = "pantheonsent_banner.png"
itemIcon = "minecraft:totem_of_undying"
displayURL = "https://modrinth.com/project/pantheonsent"

[modproperties.pantheonsent]
catalogueImageIcon = "pantheonsent_icon.png"

[[dependencies.pantheonsent]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pantheonsent]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pantheonsent]]
modId = "palladium"
mandatory = true
versionRange = "[4.0.6,)"
ordering = "AFTER"
side = "BOTH"
